; Listing generated by Microsoft (R) Optimizing Compiler Version 19.15.26729.0 

	TITLE	C:\Users\Alisher\Desktop\University\2018-2019 Winter\COIS2300\Labs\Lab 7\Lab7\Lab7\Lab7.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

msvcjmc	SEGMENT
__AC32701A_pch.h DB 01H
__2ABF52E4_lab7.pch DB 01H
__86A46991_xstddef DB 01H
__71BBFE83_utility DB 01H
__80ECD3C5_streambuf DB 01H
__A3D3B529_ostream DB 01H
__C0038013_istream DB 01H
__6FFD1BDC_xstring DB 01H
__0D6D97F6_lab7.cpp DB 01H
__AA1182C5_ios DB 01H
__2E4409FA_xlocnum DB 01H
__D7FEF932_xiosbase DB 01H
__830E8A2A_system_error DB 01H
__3C53980A_xcall_once.h DB 01H
__B0C36FED_xlocale DB 01H
__CE98FDDF_xfacet DB 01H
__E2DDAAD0_memory DB 01H
__EE1B8E21_xlocinfo DB 01H
__7C512EE2_ctype.h DB 01H
__C57511A8_vcruntime_typeinfo.h DB 01H
__824C6B79_stdexcept DB 01H
__A040127E_xatomic0.h DB 01H
__501E5FA1_xmemory0 DB 01H
__814D9EF0_xutility DB 01H
__929A73D8_iosfwd DB 01H
__5E73A65E_limits DB 01H
__5D5F9F21_wchar.h DB 01H
__33831CCF_stat.h DB 01H
__90701A18_corecrt_wtime.h DB 01H
__BE076D93_corecrt_wio.h DB 01H
__FEB88A67_corecrt_wconio.h DB 01H
__0B025124_exception DB 01H
__8AB4B352_vcruntime_exception.h DB 01H
__6AAA6594_malloc.h DB 01H
__B1799763_type_traits DB 01H
__78F4D6C6_string.h DB 01H
__9CE3A74D_corecrt_wstring.h DB 01H
__9F081559_corecrt_memory.h DB 01H
__07523DAF_corecrt_memcpy_s.h DB 01H
__A3797CDC_stdio.h DB 01H
__BAC7FC50_corecrt_wstdio.h DB 01H
__320E01E0_corecrt_stdio_config.h DB 01H
__457D4847_xtgmath.h DB 01H
__421A99BA_cmath DB 01H
__46B67B08_cstdlib DB 01H
__EDC08FAA_corecrt_math.h DB 01H
__FE874262_stdlib.h DB 01H
__545EB0C3_vcruntime_new.h DB 01H
msvcjmc	ENDS
PUBLIC	?__empty_global_delete@@YAXPAX@Z		; __empty_global_delete
PUBLIC	?__empty_global_delete@@YAXPAXI@Z		; __empty_global_delete
PUBLIC	_main
PUBLIC	__real@3f800000
PUBLIC	__real@3ff0000000000000
PUBLIC	__real@4b189680
EXTRN	__imp_?precision@ios_base@std@@QAE_J_J@Z:PROC
EXTRN	__imp_??6?$basic_ostream@DU?$char_traits@D@std@@@std@@QAEAAV01@M@Z:PROC
EXTRN	__imp_?get@?$basic_istream@DU?$char_traits@D@std@@@std@@QAEHXZ:PROC
EXTRN	@__CheckForDebuggerJustMyCode@4:PROC
EXTRN	__imp_?cin@std@@3V?$basic_istream@DU?$char_traits@D@std@@@1@A:BYTE
EXTRN	__imp_?cout@std@@3V?$basic_ostream@DU?$char_traits@D@std@@@1@A:BYTE
EXTRN	__fltused:DWORD
;	COMDAT __real@4b189680
CONST	SEGMENT
__real@4b189680 DD 04b189680r			; 1e+07
CONST	ENDS
;	COMDAT __real@3ff0000000000000
CONST	SEGMENT
__real@3ff0000000000000 DQ 03ff0000000000000r	; 1
CONST	ENDS
;	COMDAT __real@3f800000
CONST	SEGMENT
__real@3f800000 DD 03f800000r			; 1
CONST	ENDS
; Function compile flags: /Ogtp
; File c:\users\alisher\desktop\university\2018-2019 winter\cois2300\labs\lab 7\lab7\lab7\lab7.cpp
;	COMDAT _main
_TEXT	SEGMENT
_main	PROC						; COMDAT
	mov	ecx, OFFSET __0D6D97F6_lab7.cpp
	call	@__CheckForDebuggerJustMyCode@4
	mov	edx, DWORD PTR __imp_?cout@std@@3V?$basic_ostream@DU?$char_traits@D@std@@@1@A
	push	0
	push	0
	mov	eax, DWORD PTR [edx]
	mov	ecx, DWORD PTR [eax+4]
	add	ecx, edx
	call	DWORD PTR __imp_?precision@ios_base@std@@QAE_J_J@Z
	movss	xmm0, DWORD PTR __real@3f800000
	xorps	xmm3, xmm3
	movsd	xmm4, QWORD PTR __real@3ff0000000000000
	movss	xmm5, DWORD PTR __real@4b189680
	npad	4
$LL2@main:

	cvtps2pd xmm2, xmm0
	movaps	xmm1, xmm4
	divsd	xmm1, xmm2
	cvtps2pd xmm0, xmm3

	addsd	xmm2, xmm4
	xorps	xmm3, xmm3
	addsd	xmm1, xmm0
	cvtpd2ps xmm0, xmm2
	cvtsd2ss xmm3, xmm1
	comiss	xmm5, xmm0
	jae	SHORT $LL2@main

	push	ecx
	mov	ecx, DWORD PTR __imp_?cout@std@@3V?$basic_ostream@DU?$char_traits@D@std@@@1@A
	movss	DWORD PTR [esp], xmm3
	call	DWORD PTR __imp_??6?$basic_ostream@DU?$char_traits@D@std@@@std@@QAEAAV01@M@Z

	mov	ecx, DWORD PTR __imp_?cin@std@@3V?$basic_istream@DU?$char_traits@D@std@@@1@A
	call	DWORD PTR __imp_?get@?$basic_istream@DU?$char_traits@D@std@@@std@@QAEHXZ

	xor	eax, eax

	ret	0
_main	ENDP
_TEXT	ENDS
; Function compile flags: /Ogtp
; File c:\users\alisher\desktop\university\2018-2019 winter\cois2300\labs\lab 7\lab7\lab7\lab7.cpp
;	COMDAT ?__empty_global_delete@@YAXPAXI@Z
_TEXT	SEGMENT
___formal$ = 8						; size = 4
___formal$ = 12						; size = 4
?__empty_global_delete@@YAXPAXI@Z PROC			; __empty_global_delete, COMDAT
	mov	ecx, OFFSET __0D6D97F6_lab7.cpp
	jmp	@__CheckForDebuggerJustMyCode@4
?__empty_global_delete@@YAXPAXI@Z ENDP			; __empty_global_delete
_TEXT	ENDS
; Function compile flags: /Ogtp
; File c:\users\alisher\desktop\university\2018-2019 winter\cois2300\labs\lab 7\lab7\lab7\lab7.cpp
;	COMDAT ?__empty_global_delete@@YAXPAX@Z
_TEXT	SEGMENT
___formal$ = 8						; size = 4
?__empty_global_delete@@YAXPAX@Z PROC			; __empty_global_delete, COMDAT
	mov	ecx, OFFSET __0D6D97F6_lab7.cpp
	jmp	@__CheckForDebuggerJustMyCode@4
?__empty_global_delete@@YAXPAX@Z ENDP			; __empty_global_delete
_TEXT	ENDS
END
