; Listing generated by Microsoft (R) Optimizing Compiler Version 19.15.26729.0 

	TITLE	C:\Users\Alisher\Desktop\University\2018-2019 Winter\COIS2300\Labs\Lab 7\Lab7\Lab7\pch.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

PUBLIC	___@@_PchSym_@00@UfhvihUzorhsviUwvhpglkUfmrevihrgbUCABIRCABJLdrmgviUxlrhCDAAUozyhUozyLHUozyHUozyHUwvyftUkxsOlyq@4B2008FD98C1DD4
;	COMDAT ___@@_PchSym_@00@UfhvihUzorhsviUwvhpglkUfmrevihrgbUCABIRCABJLdrmgviUxlrhCDAAUozyhUozyLHUozyHUozyHUwvyftUkxsOlyq@4B2008FD98C1DD4
_BSS	SEGMENT
___@@_PchSym_@00@UfhvihUzorhsviUwvhpglkUfmrevihrgbUCABIRCABJLdrmgviUxlrhCDAAUozyhUozyLHUozyHUozyHUwvyftUkxsOlyq@4B2008FD98C1DD4 DD 01H DUP (?)
_BSS	ENDS
msvcjmc	SEGMENT
__2ABF52E4_lab7.pch DB 01H
msvcjmc	ENDS
END
